## Getting data

In [58]:
!wget https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv

--2022-09-11 22:27:25--  https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv
Resolviendo raw.githubusercontent.com (raw.githubusercontent.com)... 2606:50c0:8003::154, 2606:50c0:8001::154, 2606:50c0:8002::154, ...
Conectando con raw.githubusercontent.com (raw.githubusercontent.com)[2606:50c0:8003::154]:443... conectado.
Petición HTTP enviada, esperando respuesta... 200 OK
Longitud: 1475504 (1.4M) [text/plain]
Grabando a: «data.csv.2»

data.csv.2          100%[===================>]   1.41M  2.37MB/s    en 0.6s    

2022-09-11 22:27:25 (2.37 MB/s) - «data.csv.2» guardado [1475504/1475504]



## Libraries

In [59]:
import pandas as pd
import numpy as np

In [60]:
np.__version__ # Question 1

'1.23.3'

## Load data

In [61]:
df = pd.read_csv('data.csv')
df.head()

Make       Model  Year             Engine Fuel Type  Engine HP  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   
1  BMW    1 Series  2011  premium unleaded (required)      300.0   
2  BMW    1 Series  2011  premium unleaded (required)      300.0   
3  BMW    1 Series  2011  premium unleaded (required)      230.0   
4  BMW    1 Series  2011  premium unleaded (required)      230.0   

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               6.0            MANUAL  rear wheel drive              2.0   
1               6.0            MANUAL  rear wheel drive              2.0   
2               6.0            MANUAL  rear wheel drive              2.0   
3               6.0            MANUAL  rear wheel drive              2.0   
4               6.0            MANUAL  rear wheel drive              2.0   

                         Market Category Vehicle Size Vehicle Style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe   
1                     Luxury,Performance      Compact   Convertible   
2                Luxury,High-Performance      Compact         Coupe   
3                     Luxury,Performance      Compact         Coupe   
4                                 Luxury      Compact   Convertible   

   highway MPG  city mpg  Popularity   MSRP  
0           26        19        3916  46135  
1           28        19        3916  40650  
2           28        20        3916  36350  
3           28        18        3916  29450  
4           28        18        3916  34500

## Answers

In [62]:
print(f'Number of rows: {df.shape[0]}') # Question 2

Number of rows: 11914


In [64]:
print('Top 5 - most popular  car manufacturers:')
df.Make.value_counts().sort_values(ascending = False).head(5) # Question 3

Top 5 - most popular  car manufacturers:


Chevrolet     1123
Ford           881
Volkswagen     809
Toyota         746
Dodge          626
Name: Make, dtype: int64

In [111]:
print(f'Car manufactures: ')
(df.Make.unique())

Car manufactures: 


array(['BMW', 'Audi', 'FIAT', 'Mercedes-Benz', 'Chrysler', 'Nissan',
       'Volvo', 'Mazda', 'Mitsubishi', 'Ferrari', 'Alfa Romeo', 'Toyota',
       'McLaren', 'Maybach', 'Pontiac', 'Porsche', 'Saab', 'GMC',
       'Hyundai', 'Plymouth', 'Honda', 'Oldsmobile', 'Suzuki', 'Ford',
       'Cadillac', 'Kia', 'Bentley', 'Chevrolet', 'Dodge', 'Lamborghini',
       'Lincoln', 'Subaru', 'Volkswagen', 'Spyker', 'Buick', 'Acura',
       'Rolls-Royce', 'Maserati', 'Lexus', 'Aston Martin', 'Land Rover',
       'Lotus', 'Infiniti', 'Scion', 'Genesis', 'HUMMER', 'Tesla',
       'Bugatti'], dtype=object)

In [66]:
print(f'Number of unique Audi models: {df[df.Make=="Audi"].Model.nunique()}') # Question 4

Number of unique Audi models: 34


In [63]:
df.isna().sum().sort_values() # Question 5

Make                    0
Model                   0
Year                    0
Transmission Type       0
Driven_Wheels           0
Vehicle Size            0
Vehicle Style           0
highway MPG             0
city mpg                0
Popularity              0
MSRP                    0
Engine Fuel Type        3
Number of Doors         6
Engine Cylinders       30
Engine HP              69
Market Category      3742
dtype: int64

In [67]:
median_before = df.median()
median_before

/var/folders/dq/xfx5t1t5513g62zytzm288840000gn/T/ipykernel_25016/1489813875.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  median_before = df.median()


Year                 2015.0
Engine HP             227.0
Engine Cylinders        6.0
Number of Doors         4.0
highway MPG            26.0
city mpg               18.0
Popularity           1385.0
MSRP                29995.0
dtype: float64

In [72]:
df = df.fillna(df.median().round(1))

/var/folders/dq/xfx5t1t5513g62zytzm288840000gn/T/ipykernel_25016/1153686878.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  df = df.fillna(df.median().round(1))


In [75]:
median_after = df.median()
median_after

/var/folders/dq/xfx5t1t5513g62zytzm288840000gn/T/ipykernel_25016/3260015154.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  median_after = df.median()


Year                 2015.0
Engine HP             227.0
Engine Cylinders        6.0
Number of Doors         4.0
highway MPG            26.0
city mpg               18.0
Popularity           1385.0
MSRP                29995.0
dtype: float64

In [112]:
median_before == median_after # Question 6

Year                True
Engine HP           True
Engine Cylinders    True
Number of Doors     True
highway MPG         True
city mpg            True
Popularity          True
MSRP                True
dtype: bool

In [94]:
df_lotus = df.loc[df.Make == 'Lotus',["Engine HP", "Engine Cylinders"]].copy()
df_lotus.head()

Engine HP  Engine Cylinders
3912      189.0               4.0
3913      218.0               4.0
3914      189.0               4.0
3915      189.0               4.0
3916      218.0               4.0

In [99]:
df_lotus = df_lotus.drop_duplicates().copy()
print(f'Number of rows: {df_lotus.shape[0]}')

Number of rows: 9


In [100]:
X = df_lotus.to_numpy()
X

array([[189.,   4.],
       [218.,   4.],
       [217.,   4.],
       [350.,   8.],
       [400.,   6.],
       [276.,   6.],
       [345.,   6.],
       [257.,   4.],
       [240.,   4.]])

In [103]:
XT = X.T
XT

array([[189., 218., 217., 350., 400., 276., 345., 257., 240.],
       [  4.,   4.,   4.,   8.,   6.,   6.,   6.,   4.,   4.]])

In [105]:
XTX =  np.dot(XT, X)
XTX

array([[7.31684e+05, 1.34100e+04],
       [1.34100e+04, 2.52000e+02]])

In [106]:
y = [1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800]
y

[1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800]

In [107]:
XTX_Inv = np.linalg.inv(XTX)
XTX_Inv

array([[ 5.53084235e-05, -2.94319825e-03],
       [-2.94319825e-03,  1.60588447e-01]])

In [114]:
w = np.dot(np.dot(XTX_Inv, XT), y)
print(f'First element of w is: {w[0]}')

First element of w is: 4.594944810094551
